FROM golang:1.23 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /app/main ./cmd/main.go

RUN mkdir -p /app/storage \
    && touch /app/storage/mystorage.json \
    && chmod -R 777 /app/storage

# debug
# RUN cat /app/cmd/mai?n.go,
# RUN ls -lh /app/main

CMD ["/app/main"]
