FROM golang:1.23 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN --mount=type=cache,target="/root/.cache/go-build" go build -o /app/main ./cmd/main.go

RUN mkdir -p /app/storage \
    && touch /app/storage/mystorage.json \
    && chmod -R 777 /app/storage

CMD ["/app/main"]
